@baseUrl = https://localhost:5001

@apiBaseUrl = {{baseUrl}}/api
@graphQlBaseUrl = {{baseUrl}}/graphql

@domain = City

@domainUrl = {{apiBaseUrl}}/{{domain}}

# Get all cities
GET {{domainUrl}}
###

# Get city by id
GET {{domainUrl}}/id/1
###

# Create city
POST {{domainUrl}}

{
    "id": 11,
    "first_name": "Manoj",
    "middle_name": "Mad",
    "last_name": "Waikar"
}
###

# Update city
PUT {{domainUrl}}/id/11

{
    "first_name": "Manoj",
    "middle_name": "M",
    "last_name": "Waikar"
}
###

# Delete city
DELETE {{domainUrl}}/id/11
###

#### GraphQL examples ####

# Get cities with country
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    cities {
        items {
            id
            name
            short_name
            country {
                id
                name
            }
        }
    }
}
###

# Order by ex - Get cities with country, ordered by city name
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    cities(orderBy: { name: ASC }) {
        items {
            id
            name
            short_name
            country {
                id
                name
            }
        }
    }
}
###

# Filter ex - Get cities with 'er' in the name (with country)
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    cities(filter: { name: { contains: "er" }}) 
    {
        items {
            id
            name
            short_name
            country {
                id
                name
            }
        }
    }
}
###

# Get city by id (with country)
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    city_by_pk(id: 5) {
        id
        name
        short_name
        country {
            id
            name
        }
    }
}
###
