@baseUrl = https://localhost:5001

@apiBaseUrl = {{baseUrl}}/api
@graphQlBaseUrl = {{baseUrl}}/graphql

@domain = CloudProvider

@domainUrl = {{apiBaseUrl}}/{{domain}}

# Get all cloud providers
GET {{domainUrl}}
###

# Get cloud provider by id
GET {{domainUrl}}/id/1
###

# Create cloud provider
POST {{domainUrl}}

{
    "id": 11,
    "first_name": "Manoj",
    "middle_name": "Mad",
    "last_name": "Waikar"
}
###

# Update cloud provider
PUT {{domainUrl}}/id/11

{
    "first_name": "Manoj",
    "middle_name": "M",
    "last_name": "Waikar"
}
###

# Delete cloud provider
DELETE {{domainUrl}}/id/11
###

#### GraphQL examples ####

# Get cloud providers with data centers
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    cloudProviders {
        items {
            id
            name
            datacenters {
                items {
                    id
                    name
                    city {
                        id
                        name
                    }
                }
            }
        }
    }
}
###

# Order by ex - Get cities with country, ordered by city name
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    cities(orderBy: { name: ASC }) {
        items {
            id
            name
            Shortname
            country {
                id
                name
            }
        }
    }
}
###

# Filter ex - Get cities with 'er' in the name (with country)
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    cities(filter: { name: { contains: "er" }}) 
    {
        items {
            id
            name
            Shortname
            country {
                id
                name
            }
        }
    }
}
###

# Get city by id (with country)
POST {{graphQlBaseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    city_by_pk(id: 5) {
        id
        name
        Shortname
        country {
            id
            name
        }
    }
}
###
